baseurl = "https://lek-nrw.de/"
title = "LEK NRW"
# theme = "hugo-theme-cleanwhite"
theme = "lek-nrw-theme"
languageCode = "de-de"
preserveTaxonomyNames = true
hasCJKLanguage = false

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS"]

[params]
  # Kategorien verstecken!
  hideCategories = true
  # Logo anstatt Title im Schriftzug
  logo = "img/logo-lek-nrw-black.png"      # Pfad relativ zu /static
  showLogoOnHero = true

  ## Impressum Variablen - Beginn
  # Institution
  impressum1 = "Landeselternkonferenz NRW"
  # Verantwortlicher/Vorsitzender
  impressum2 = "Hinrich Pich"
  # Adresse: Strasse und Hausnummer
  impressum3 = "Sperberweg 25"
  # Adresse: PLZ und Ort
  impressum4 = "53757 Sankt Augustin"
  # E-Mailadresse
  impressum5 = "vorstand (äffchen) lek-nrw (punkt) de"
  ## Impressum Variablen - Ende 
  header_image = "img/home-bg-lek-hero-hell.png"
  SEOTitle = "LEK - Landeselternkonferenz NRW - Der Dachverband der Kreis und Stadtschulpflegschaften in NRW"
  description = "LEK - Landeselternkonferenz NRW - Der Dachverband der Kreis und Stadtschulpflegschaften in NRW"
  keyword = "LEK, Landeselternkonferenz, Landeselternkonferenz NRW, LEK NRW, Dachverband, Kreisschulpflegschaft, Stadtschulpflegschaft, Stadtschulpflegschaften NRW, Kreisschulpflegschaft NRW, Schulpflegschaft"
  slogan = "Der Dachverband der Kreis und Stadtschulpflegschaften in NRW"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Das war wohl nichts... 404"
  omit_categories = false

  
  [params.social]
  rss            = true 
  email          = "youremail@gmail.com"
  facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  instagram     = "full profile url in instagram"
  github         = "https://github.com/yourgithub"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  
[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']

[menu]
  [[menu.main]]
    name = "Über uns"
    url = "/ueber-uns"
    weight = 1
  [[menu.main]]
    name = "Vorstand"
    url = "/ueber-uns/vorstand"
    parent = "Über uns"
    weight = 1   

  [[menu.main]]
    name = "Mitglieder"
    url = "/ueber-uns/mitglieder"
    parent = "Über uns"
    weight = 3        
  [[menu.main]]
    name = "Termine"
    url = "/termine/"
    identifier = "termine"
    weight = 2
    pre = "hidden"

  [[menu.main]]
    name = "Veröffentlichungen"
    url = "/veroeffentlichungen/"
    identifier = "Veröffentlichungen"
    weight = 200

  [[menu.main]]
    name = "Stellungsnahmen"
    url = "/veroeffentlichungen/stellungsnahmen/"
    parent = "Veröffentlichungen"
    weight = 201

  [[menu.main]]
    name = "Pressemeldungen"
    url = "/veroeffentlichungen/pressemeldungen/"
    parent = "Veröffentlichungen"
    weight = 202 
 
  # Hauptmenüpunkt
  [[menu.main]]
    name = "Links"
    url = "/links/"
    identifier = "links"
    weight = 300

  # Submenüs
  [[menu.main]]
    name = "Schulverwaltung"
    url = "/links/schulverwaltung/"
    parent = "links"
    weight = 301

  [[menu.main]]
    name = "Verbände"
    url = "/links/verbaende/"
    parent = "links"
    weight = 302

  # Footer 
  [[menu.footer]] 
    name = "Impressum" 
    url = "/impressum/" 
    weight = 4 
  
  [[menu.footer]] 
    name = "Datenschutz" 
    url = "/datenschutz/" 
    weight = 3 
  


  [[menu.footer]] 
    name = "Satzung" 
    url = "/satzung/" 
    weight = 1

  # Footer 
  [[menu.hidden]] 
    name = "Kontakt" 
    url = "/kontakt/" 
    weight = 2
    pre = "hidden"
  
  [[menu.hidden]]
    name = "Arbeitsgruppen"
    url = "/ueber-uns/arbeitsgruppen"
    parent = "Über uns"
    weight = 2
    pre = "hidden"
  
  [[menu.hidden]]
    name = "Offene Briefe"
    url = "/veroeffentlichungen/offene-briefe/"
    parent = "Veröffentlichungen"
    weight = 203    
  
